spring:
  main:
    banner-mode: off
server:
  port: ${PORT:80}
logging:
  level:
    root: ${LOG_LEVEL:INFO}
vk:
  confirmationCode: ${VK_GROUP_CONFIRMATION_CODE}
  serviceAccessToken: ${VK_SERVICE_ACCESS_TOKEN}
  triggerString: ${VK_TRIGGER_STRING}
discord:
  botToken: ${DISCORD_BOT_TOKEN}
  guildId: ${DISCORD_GUILD_ID}
  channelId: ${DISCORD_CHANNEL_ID}
telegram:
  botToken: ${TELEGRAM_BOT_TOKEN}
  channelId: ${TELEGRAM_CHANNEL_ID}
twitch:
  clientId: ${TWITCH_CLIENT_ID}
  clientSecret: ${TWITCH_CLIENT_SECRET}
  botOAuthToken: ${TWITCH_BOT_OAUTH_TOKEN}
  channelName: ${TWITCH_CHANNEL_NAME}
