spring:
  main:
    banner-mode: off
server:
  port: ${PORT:80}
logging:
  level:
    root: ${LOG_LEVEL:INFO}
security:
  oauth2:
    client:
      clientId: ${TWITCH_CLIENT_ID}
      clientSecret: ${TWITCH_CLIENT_SECRET}
      accessTokenUri: https://id.twitch.tv/oauth2/token
      grantType: client_credentials
      clientAuthenticationScheme: form
app:
  url: ${APP_URL}
  twitch:
    pauseBetweenNotifications: ${TWITCH_PAUSE_BETWEEN_NOTIFICATIONS}
    credentials:
      userLogin: ${TWITCH_USER_LOGIN}
      clientId: ${TWITCH_CLIENT_ID}
      clientSecret: ${TWITCH_CLIENT_SECRET}

vk:
  confirmationCode: ${VK_GROUP_CONFIRMATION_CODE}
  serviceAccessToken: ${VK_SERVICE_ACCESS_TOKEN}
  triggerString: ${VK_TRIGGER_STRING}
discord:
  botToken: ${DISCORD_BOT_TOKEN}
  channelId: ${DISCORD_CHANNEL_ID}
telegram:
  botToken: ${TELEGRAM_BOT_TOKEN}
  channelId: ${TELEGRAM_CHANNEL_ID}
twitch:
  clientId: ${TWITCH_CLIENT_ID}
  clientSecret: ${TWITCH_CLIENT_SECRET}
  botOAuthToken: ${TWITCH_BOT_OAUTH_TOKEN}
